name: tr02py
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - matplotlib=3.9.2
  - pandas=2.2.3
  - pillow=11.0.0
  - pip=24.2
  - streamlit=1.40.1
  - pip:
      - extra-streamlit-components==0.1.71
      - streamlit-authenticator==0.2.3
